name: 构建跨平台可执行文件

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # 允许手动触发

jobs:
  build-windows:
    name: 构建Windows可执行文件
    runs-on: windows-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PySimpleGUI openpyxl
        
    - name: 构建Windows可执行文件
      run: |
        pyinstaller --onefile --noconsole --name=文件比较器 --hidden-import=openpyxl --hidden-import=PySimpleGUI main.py
        
    - name: 上传Windows构建结果
      uses: actions/upload-artifact@v3
      with:
        name: windows-executable
        path: |
          dist/文件比较器.exe
          README.md
        retention-days: 30

  build-macos:
    name: 构建macOS可执行文件
    runs-on: macos-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装系统依赖
      run: |
        brew install python-tk
        
    - name: 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PySimpleGUI openpyxl
        
    - name: 构建macOS可执行文件
      run: |
        pyinstaller --onedir --windowed --name=文件比较器 --hidden-import=openpyxl --hidden-import=PySimpleGUI main.py
        
    - name: 创建DMG包（可选）
      run: |
        # 安装create-dmg工具
        brew install create-dmg
        
        # 创建临时目录
        mkdir -p dmg_temp
        cp -R "dist/文件比较器.app" dmg_temp/
        cp README.md dmg_temp/
        
        # 创建DMG文件
        create-dmg \
          --volname "文件比较器" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "文件比较器.app" 200 190 \
          --hide-extension "文件比较器.app" \
          --app-drop-link 600 185 \
          "文件比较器.dmg" \
          "dmg_temp/" || true  # 忽略错误，因为可能没有图标
        
    - name: 上传macOS构建结果
      uses: actions/upload-artifact@v3
      with:
        name: macos-executable
        path: |
          dist/
          文件比较器.dmg
          README.md
        retention-days: 30

  build-linux:
    name: 构建Linux可执行文件
    runs-on: ubuntu-latest
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-tk
        
    - name: 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller PySimpleGUI openpyxl
        
    - name: 构建Linux可执行文件
      run: |
        pyinstaller --onefile --name=文件比较器 --hidden-import=openpyxl --hidden-import=PySimpleGUI main.py
        
    - name: 上传Linux构建结果
      uses: actions/upload-artifact@v3
      with:
        name: linux-executable
        path: |
          dist/文件比较器
          README.md
        retention-days: 30

  create-release:
    name: 创建发布版本
    needs: [build-windows, build-macos, build-linux]
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v4
      
    - name: 下载所有构建结果
      uses: actions/download-artifact@v3
      
    - name: 准备发布文件
      run: |
        mkdir -p release
        
        # Windows文件
        if [ -d "windows-executable" ]; then
          cp windows-executable/文件比较器.exe release/文件比较器-Windows.exe
        fi
        
        # macOS文件
        if [ -d "macos-executable" ]; then
          cd macos-executable
          if [ -f "文件比较器.dmg" ]; then
            cp 文件比较器.dmg ../release/文件比较器-macOS.dmg
          fi
          if [ -d "dist" ]; then
            tar -czf ../release/文件比较器-macOS.tar.gz -C dist .
          fi
          cd ..
        fi
        
        # Linux文件
        if [ -d "linux-executable" ]; then
          cp linux-executable/文件比较器 release/文件比较器-Linux
          chmod +x release/文件比较器-Linux
        fi
        
        # 列出所有文件
        ls -la release/
        
    - name: 创建GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        files: release/*
        generate_release_notes: true
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}